/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false` (hash: de015f81fd2be40de4838f60d489e175)
declare namespace Cloudflare {
	interface Env {
		RP_ID: "localhost";
		ORIGIN: "http://localhost:5173";
		CHALLENGE_TTL_MS: "300000";
		SESSION_TTL_MS: "604800000";
		DB: D1Database;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RP_ID" | "ORIGIN" | "CHALLENGE_TTL_MS" | "SESSION_TTL_MS">> {}
}
