/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false` (hash: e0fd6fa0028b52b7f39dd5cdd7292ccb)
declare namespace Cloudflare {
	interface Env {
		RP_ID: "localhost";
		ORIGIN: "http://localhost:5173";
		CHALLENGE_TTL_MS: "300000";
		SESSION_TTL_MS: "604800000";
		DB: D1Database;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
