/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsNewRouteImport } from './routes/snippets.new'
import { Route as SnippetsIdRouteImport } from './routes/snippets.$id'
import { Route as SnippetsIdEditRouteImport } from './routes/snippets.$id.edit'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsNewRoute = SnippetsNewRouteImport.update({
  id: '/snippets/new',
  path: '/snippets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIdRoute = SnippetsIdRouteImport.update({
  id: '/snippets/$id',
  path: '/snippets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIdEditRoute = SnippetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SnippetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/snippets/$id': typeof SnippetsIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets/$id/edit': typeof SnippetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/snippets/$id': typeof SnippetsIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets/$id/edit': typeof SnippetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/snippets/$id': typeof SnippetsIdRouteWithChildren
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets/$id/edit': typeof SnippetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tags'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tags'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tags'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TagsRoute: typeof TagsRoute
  SnippetsIdRoute: typeof SnippetsIdRouteWithChildren
  SnippetsNewRoute: typeof SnippetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/new': {
      id: '/snippets/new'
      path: '/snippets/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof SnippetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$id': {
      id: '/snippets/$id'
      path: '/snippets/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof SnippetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$id/edit': {
      id: '/snippets/$id/edit'
      path: '/edit'
      fullPath: '/snippets/$id/edit'
      preLoaderRoute: typeof SnippetsIdEditRouteImport
      parentRoute: typeof SnippetsIdRoute
    }
  }
}

interface SnippetsIdRouteChildren {
  SnippetsIdEditRoute: typeof SnippetsIdEditRoute
}

const SnippetsIdRouteChildren: SnippetsIdRouteChildren = {
  SnippetsIdEditRoute: SnippetsIdEditRoute,
}

const SnippetsIdRouteWithChildren = SnippetsIdRoute._addFileChildren(
  SnippetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TagsRoute: TagsRoute,
  SnippetsIdRoute: SnippetsIdRouteWithChildren,
  SnippetsNewRoute: SnippetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
